### ISSUE TITLE
When the players die they are not born in spawn.

### ISSUE THREAD

**Issue by farukalpay** [montlikadani/SetTheSpawn#2]
### Describe the bug (required)
When the players die they are not born in spawn.

### Plugin version (required)
V2.0

### Console error (required)
`30.01.2019 - 12:03:36 - [INFO] The 'config.yml' file successfully created!
30.01.2019 - 12:03:36 - [INFO] The 'messages.yml' file successfully created!
30.01.2019 - 12:03:36 - [INFO] The 'spawns.yml' file successfully created!
30.01.2019 - 12:03:36 - [INFO] You're running the latest version.
30.01.2019 - 12:03:36 - [INFO] Metrics enabled.
30.01.2019 - 12:05:41 - [INFO] New spawn saved to spawns.yml file.
30.01.2019 - 12:09:35 - [INFO] You're running the latest version.
30.01.2019 - 12:09:35 - [INFO] Metrics enabled.
30.01.2019 - 12:09:44 - [WARNING] The spawn has not set in CraftWorld{name=world} world!
30.01.2019 - 12:10:23 - [WARNING] The spawn has not set in CraftWorld{name=world} world!
30.01.2019 - 12:12:55 - [WARNING] The spawn has not set in CraftWorld{name=world} world!
30.01.2019 - 12:14:02 - [WARNING] The spawn has not set in CraftWorld{name=world} world!
30.01.2019 - 12:18:38 - [INFO] New spawn saved to spawns.yml file.
30.01.2019 - 12:20:34 - [WARNING] The spawn has not set in CraftWorld{name=world} world!
`

config.yml
```
#=================================OOO====================================#
#                    SetTheSpawn Configuration File                      #
#=================================OOO====================================#
# config.yml file. Plugin version: 2.0                                   #
# Author, created by: montlikadani                                       #
#=================================OOO====================================#
# [Default configuration]                                                #
# https://github.com/montlikadani/SetTheSpawn/blob/master/config.yml     #
#                                                                        #
# [Placeholders]                                                         #
# https://github.com/montlikadani/SetTheSpawn/wiki/Placeholders          #
#                                                                        #
# [Tips]                                                                 #
# - Use color coding '&' character, on this page:                        #
# http://minecraft.gamepedia.com/Formatting_codes                        #
# - If you find a bug, send here:                                        #
# https://github.com/montlikadani/SetTheSpawn/issues                     #
# - If the string is empty does not send the message.                    #
#=================================OOO====================================#

#=========================================#
#                Settings                 #
#=========================================#
# Use the Vault plugin for the plugin.
vault: true

# How many seconds do you have to wait for a player to be teleported?
# If 0 you do not have to wait.
teleport-delay: 0 # In seconds!

# Teleport progress bar.
progress-bar:
  enable: false
  # Progress bar size.
  bar-size: 30.0
  # Bar update fast in ticks.
  fast: 2
  # Teleport progress display mark.
  mark: '|'
  # When the teleport is ready.
  done-color: '&a&l'
  # When teleport is not ready yet.
  not-done-color: '&c&l'
  # Use %output%, %time% placeholder.
  message-format: '&aTeleporting in:&7&l [%output%&7&l]&6 (&8%time%&6)'

# If the spawn can not be found, teleport it to the world spawn?
teleport-to-world-spawn-if-spawn-not-found: true

# Teleport op players to spawn. (Sign & spawn command)
# If false not teleport op players.
# If true teleport op players to spawn.
# This only sign & command work. (If everybody teleport)
teleport-op-players: true

# A player teleported to the spawn, how many seconds to protect the player from damage?
# Set 0 to disable.
no-damage-time: 0

# Message when other player was teleported the target player to the spawn.
# Use %sender%, %newline%, %prefix% placeholder.
other-player-teleported: '&e%sender%&a teleported you to spawn.'

# Is it a spawn setting in separate worlds?
# This is typical for each function!
# If true, it will write to the spawns.yml file in the world where the player is currently in (setup).
# If it is false, it will write to the spawns.yml file, the world name for the coordinates, and so on.
per-world-spawn: false

# Teleport to the set player bed spawn. If the player bed spawn not found, teleports to the spawn is default.
# The bed location not manage by the plugin!
teleport-to-bed-spawn: true

# In which worlds can spawn not be set?
disabled-worlds: []

# Disable spawn command in pvp.
disable-spawn-in-pvp:
  enable: false
  # Command disabling time in seconds.
  time: 5
  # Message when you attack a player or attack you.
  message: '&cNow you can not teleport to spawn because you''re still fighting with a player.'

# Check if the player is flying mode?
# If it is true, it will cancel the teleport delay.
# If it is false, you can teleport in flight too.
check-fly-before-teleport:
  enable: false
  message: '&cYou can not teleport to the spawn in fly mode!%newline%&cTeleportation cancelled!'

# When a player presses the SHIFT button while teleporting, and sits in snake mode, will it cancel teleportation?
check-sneak-while-teleport:
  enable: false
  message: '&cTeleporting is canceled because snake mode is enabled.'

# Cost /spawn command or sign usage.
# This requires a Vault plugin.
spawn-cost:
  enable: false
  enable-permission: true
  # If this is specified at the rank, they can use the /spawn command without payment.
  # If not specified, the /spawn command must be paid.
  permission: 'setthespawn.bypass.spawncost'
  cost: 3.0
  # Sign usage price. (Same as /spawn command.)
  sign:
    enable: false
    enable-permission: true
    # If this is specified at the rank, they can use the spawn sign without payment.
    # If not specified, the spawn sign usage must be paid.
    permission: 'setthespawn.bypass.signcost'
    cost: 2.0

# Cancel teleport if:
cancel-teleport:
  # Player was moved.
  move:
    enable: false
    # Message when the player moved.
    teleport-canceled: '&cTeleport cancelled, you can''t move!'
    # If true when the player moves, the teleport delay will cancel.
    # If false when the player moves, the teleport delay does NOT cancel it.
    enable-permission: true
    permission: 'setthespawn.bypass.movement'
    # If the player moved during teleporting, would the player pay for it or not?
    pay-if-moved:
      enable: false
      cost: 0.20
      enable-permission: true
      permission: 'setthespawn.bypass.spawn.movedcost'
      # Use %cost% placeholder.
      no-money: '&cYou do not have enough money to move during teleport.&e Cost:&a $%cost%'
  # Player was jump.
  jump:
    enable: false
    # Message when the player jumped.
    teleport-canceled: '&cTeleport cancelled, you can''t jump!'
    # If true when the player jump, the teleport delay will cancel.
    # If false when the player jump, the teleport delay does NOT cancel it.
    enable-permission: true
    permission: 'setthespawn.bypass.jump'
    # If the player jumped during teleporting, would the player pay for it or not?
    pay-if-jumped:
      enable: false
      cost: 0.15
      enable-permission: true
      permission: 'setthespawn.bypass.spawn.jumpedcost'
      # Use %cost% placeholder.
      no-money: '&cYou do not have enough money to jump in teleport.&e Cost:&a $%cost%'
  # When the player is attacked.
  damage:
    enable: false
    # Message when the other player attacked.
    teleport-canceled: '&cTeleport cancelled, you are in combat!'
    # If true when the player is attacked, the teleport delay will cancel.
    # If false when the player is attacked, the teleport delay does NOT cancel it.
    enable-permission: true
    permission: 'setthespawn.bypass.damage'
    # If the player damage during teleporting, would the player pay for it or not?
    pay-if-damage:
      enable: false
      cost: 0.5
      enable-permission: true
      permission: 'setthespawn.bypass.spawn.damagecost'
      # Use %cost% placeholder.
      no-money: '&cYou do not have enough money for the teleport damage.&e Cost:&a $%cost%'

# When a player is being teleported, will plays an effect?
teleport-effect:
  enable: false
  # All effects:
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html
  effect: ENDER_SIGNAL
  duration: 10

# Teleport sound playback.
teleport-sound:
  enable: false
  # All sounds:
  # 1.7.x: https://jd.bukkit.org/org/bukkit/Sound.html
  # 1.8.x: http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html
  # 1.9.x - 1.13.x: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  sound: ENDERMAN_TELEPORT
  volume: 10
  pitch: 1

# Launch firework when the player teleported to the spawn.
launch-firework:
  enable: false
  # If true, the features below do not apply to it.
  random: true
  flicker: true
  trail: true
  # All firework types: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/FireworkEffect.Type.html
  type: STAR
  # Colors 0 - 255
  colors:
  - 229,0,0
  - 0,80,0
  - 0,0,103
  # The power to launch the firework.
  power: 1

# Send title if:
title:
  # When you have started teleporting, a title will also be displayed.
  start-spawn:
    enable: false
    # Use %seconds% placeholder.
    title: '&aTeleporting in'
    subtitle: '&6%seconds%&a seconds'
    # The time it takes for the title to fade into the screen. (In ticks)
    fade-in: 10
    # The time it takes for the title to stay on the screen. (In ticks)
    stay: 30
    # The time it takes for the title to fade out of the screen. (In ticks)
    fade-out: 60
  # This is when the player has teleported to the spawn and displays the title.
  end-spawn:
    enable: false
    title: '&3Teleport'
    subtitle: '&asuccess!'
    # The time it takes for the title to fade into the screen. (In ticks)
    fade-in: 10
    # The time it takes for the title to stay on the screen. (In ticks)
    stay: 30
    # The time it takes for the title to fade out of the screen. (In ticks)
    fade-out: 60
  # When a player moves while teleporting.
  player-moved:
    enable: false
    title: '&cYou moved!'
    subtitle: '&eTeleport cancelled.'
    # The time it takes for the title to fade into the screen. (In ticks)
    fade-in: 10
    # The time it takes for the title to stay on the screen. (In ticks)
    stay: 30
    # The time it takes for the title to fade out of the screen. (In ticks)
    fade-out: 50
  # When a player jump while teleporting.
  player-jump:
    enable: false
    title: '&cYou jumped!'
    subtitle: '&eTeleport cancelled.'
    # The time it takes for the title to fade into the screen. (In ticks)
    fade-in: 10
    # The time it takes for the title to stay on the screen. (In ticks)
    stay: 30
    # The time it takes for the title to fade out of the screen. (In ticks)
    fade-out: 50
  # When teleporting player are attacked while teleporting.
  player-damage:
    enable: false
    title: '&cA player was attacked!'
    subtitle: '&eTeleport cancelled.'
    # The time it takes for the title to fade into the screen. (In ticks)
    fade-in: 10
    # The time it takes for the title to stay on the screen. (In ticks)
    stay: 30
    # The time it takes for the title to fade out of the screen. (In ticks)
    fade-out: 50

# When does the player void, will the player teleport to the spawn?
void-on-spawn:
  enable: false
  # At that point, the player will be teleported to the spawn.
  # Example: 5 - so Y:5.
  height: 0
  # If it is true, it does not hurt.
  # If it is false, it hurts.
  fall-distance: true
  # When a player void, plays an effect?
  teleport-effect:
    enable: true
    # All effects:
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html
    effect: ENDER_SIGNAL
    duration: 15
  # Message when the player has void fall and teleported to spawn.
  message: ''

# Teleport on command.
teleport-on-command:
  # Player commands.
  # Use %player%, %player-displayname%, %world%, %player-gamemode%, %player-health%, %player-max-health% placeholder.
  player-command:
    enable: false
    commands:
    - 'money'
    - 'kit'
  # Console commands.
  console-command:
    enable: false
    commands:
    - 'eco take %player% 50'
    - 'money'

# Teleport to spawn if:
spawn-teleport:
  # If the player joins the server, will it teleport to the spawn?
  player-join: false
  # If the player first joins the server, will it teleport to the spawn?
  player-first-join: true
  # When the player is died and teleported to the spawn.
  respawn: true

# Spawn sign settings.
spawn-sign:
  # Allows you to create and use the spawn sign.
  enable: false
  # If the player does not have permission to create a sign.
  no-permission-create-sign:
    # If it is true, it will break the sign.
    # If it is false, it does not break the sign.
    break-sign: false
    # If it is 'enable: true', it writes to the sign.
    setline:
      enable: false
      line0: '&cYou do not have'
      line1: '&cpermission'
      line2: '&cto create'
      line3: '&ca sign!'
  # If the spawn is not set up and what to write.
  # Use %text% placeholder.
  no-spawn:
    line0: '&c[Spawn]'
    line1: '%text%'
    line2: '%text%'
    line3: '%text%'
  # If the spawn is set and what to write.
  spawn-created:
    line0: '%color%[Spawn]' # Use %color% placeholder.
    line1: '%text%'
    line2: '%text%'
    line3: '%text%'
    everybody:
      # Use %all% placeholder.
      line0: '%color%[Spawn]' # Use %color% placeholder.
      line1: '%all%'
      line2: '%text%'
      line3: '%text%'
    # If the world spawn is set and what to write.
    per-world:
      # Use %world% placeholder.
      line0: '%color%[Spawn]' # Use %color% placeholder.
      line1: '&6%world%'
      line2: '%text%'
      line3: '%text%'
      everybody:
        # Use %all%, %world% placeholder.
        line0: '%color%[Spawn]' # Use %color% placeholder.
        line1: '%all%'
        line2: '%world%'
        line3: '%text%'
  # Play particle effect when you create a spawn sign?
  play-particle-effect-on-sign-create:
    enable: false
    # All particle effects: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
    type: EXPLOSION_LARGE
    duration: 5
  # Message when a player created a spawn sign.
  sign-created: '%prefix%&a The spawn sign was successfully created!'
  # What color should the [Spawn] first line be?
  # IMPORTANT! Colors in BIG letters!
  sign-color-line0: BLUE
  # Message when the player has broken the spawn sign.
  sign-break-msg: '&cYou broke the spawn sign!'

# Enable the gui setup?
enable-gui: false
# How many rows should the GUI have?
gui-rows: 1
# What should the name of the GUI be?
gui-name: '&5Spawn settings'
# Message when the player has opened the gui.
gui-open-message: '&aYou opened the spawn settings.'
# Close the GUI when a player clicks on an item?
close-gui-when-player-clicked-on-a-item: true
# All GUI items are here. Add slots in the same format, and it will add items to the GUI.
# How to add new item in GUI?: https://github.com/montlikadani/SetTheSpawn/wiki/How-to-add-new-item-to-GUI%3F%E2%80%8B
# Slot starts at 0 and end at 53 for a size 54 inventory.
items:
  slot-0:
    item: AIR
    command: ''
  slot-1:
    item: AIR
    command: ''
  slot-2:
    item: SIGN
    durability: 0
    name: '&3Setspawn'
    lore:
      - '&7------------'
      - '&aSet spawn command.'
      - '&7------------'
    command: setspawn
  slot-3:
    item: AIR
    command: ''
  slot-4:
    item: ENDER_PEARL
    durability: 0
    name: '&6Teleport'
    lore:
      - '&7------------'
      - '&aTeleport to the spawn.'
      - '&7------------'
    command: spawn
  slot-5:
    item: AIR
    command: ''
  slot-6:
    item: BONE
    durability: 0
    name: '&4Delete spawn'
    lore:
      - '&7------------'
      - '&5Delete spawn location.'
      - '&7------------'
    command: delspawn

#=========================================#
#             Plugin Settings             #
#=========================================#
# The SetTheSpawn plugin is disabled (false) or enabled (true).
enabled: true

# bStats Metrics.
metrics: true

# Check for updates.
check-update: true

# Log plugin messages into console.
logconsole: true

# Logging to file messages.
log-to-file: true

# Plugin enable/disable messages in console.
# Use %prefix%, %newline% placeholder.
plugin-enable: '%prefix%&a The plugin successfully enabled&6 v2.0&a!'
plugin-disable: '%prefix%&c The plugin successfully disabled!'

# The default is allowed to see the plugin information.
# Permission: setthespawn.plugininfo
default-can-see-plugin-information: false

# DO NOT CHANGE THIS!
config-version: 4
```
