### ISSUE TITLE
STS Plugin delay problem

### ISSUE THREAD

**Issue by PleisureUP** [montlikadani/SetTheSpawn#5]
### Describe your problem :
The /spawn command doesn't have the 3 or 5 seconds delay i putted in the config file 

### Details
Plugin version: lastest (9 sept 2019)
Software (Spigot lastest version) version: Minecraft Server 1.14.4

Plugins used:
BAC (MC-1.14).jar
Clearlag.jar
EasyPrefix 1.5.8.jar
EconomyShopGUI+1.1.jar
EssentialsPro_1.6.jar
EssentialsX-2.17.1.0.jar
GUIShop.jar (disabled)
GroupManager.jar
RandomTeleport.jar
RedProtect-7.6.3-b270-Universal.jar
SetTheSpawn.jar
Vault.jar

### Console error
Actually, no console errors
```
[00:24:33] [Server thread/INFO]: PleisureUP issued server command: /spawn
[00:28:47] [Server thread/INFO]: [ClearLag] Warning Ground items will be removed in 60 seconds!
[00:29:27] [Server thread/INFO]: [ClearLag] Warning Ground items will be removed in 20 seconds!
[00:29:47] [Server thread/INFO]: [ClearLag] Removed 0 Entities!
[00:31:33] [Server thread/INFO]: PleisureUP issued server command: /spawn
[00:31:42] [Server thread/INFO]: PleisureUP issued server command: /spawn
```

### Configuration file(s):

```
#=================================OOO====================================#
#                    SetTheSpawn Configuration File                      #
#=================================OOO====================================#
# config.yml file. Plugin version: 2.4                                   #
# Author, created by: montlikadani                                       #
#=================================OOO====================================#
# [Default configuration]                                                #
# https://github.com/montlikadani/SetTheSpawn/blob/master/config.yml     #
#                                                                        #
# [Placeholders]                                                         #
# https://github.com/montlikadani/SetTheSpawn/wiki/Placeholders          #
#                                                                        #
# [Tips]                                                                 #
# - Use color coding '&' character, on this page:                        #
# http://minecraft.gamepedia.com/Formatting_codes                        #
# - If you find a bug, send here:                                        #
# https://github.com/montlikadani/SetTheSpawn/issues                     #
# - If the string is empty does not send the message.                    #
#=================================OOO====================================#

# Use the Vault plugin for the plugin.
vault: true

# How many seconds do you have to wait for a player to be teleported?
# If 0 you do not have to wait.
teleport-delay: 5 # In seconds!

# This allows to send the messages repeatedly when the player starts
# teleporting and timer, or if it is false, sends the message once only.
# This can affect the use of server ram when enabled.
teleport-message-repeater: false

# Teleport progress bar.
progress-bar:
  enable: true

  # Progress bar size.
  bar-size: 30.0

  # Bar update fast in ticks.
  fast: 2

  # Teleport progress display mark.
  mark: "|"

  # When the teleport is ready.
  done-color: "&a&l"

  # When teleport is not ready yet.
  not-done-color: "&c&l"

  # Use %output%, %time% placeholder.
  message-format: "&aTeleporting in:&7&l [%output%&7&l]&6 (&8%time%&6)"

# If the spawn can not be found, teleport it to the world spawn?
teleport-to-world-spawn-if-spawn-not-found: true

# Teleport op players to spawn. (Sign & spawn command)
# If false not teleport op players.
# If true teleport op players to spawn.
# This only sign & command work. (If everybody teleport)
teleport-op-players: false

# A player teleported to the spawn, how many seconds to protect the player from damage?
# Set 0 to disable.
no-damage-time: 5

# Teleports automatically to spawn, when a player afk status is true.
# Requires Essentials!
auto-teleport-to-spawn-when-player-afk: false

# Is it a spawn setting in separate worlds?
# This is typical for each function!
# If true, it will write to the spawns.yml file in the world where the player is currently in (setup).
# If it is false, it will write to the spawns.yml file, the world name for the coordinates, and so on.
per-world-spawn: false

# Teleport to the set player bed spawn. If the player bed spawn not found, teleports to the spawn.
# The bed location not manage by this plugin!
teleport-to-bed-spawn: false

# In which worlds can spawn not be set?
disabled-worlds: []

# Disable spawn command in pvp.
disable-spawn-in-pvp:
  enable: true

  # Command disabling time in seconds.
  time: 5

  # Message when you attack a player or attack you.
  message: "&cNow you can not teleport to spawn because you're still fighting with a player."

# Check if the player is flying mode?
# If it is true, you can teleport in flight too.
# If it is false, it will cancel the teleport delay.
# This ignores with setthespawn.bypass.fly permission.
allow-spawn-when-flying: true

# Prevent spawn teleport when player is in fire?
# This ignores with setthespawn.bypass.fire permission.
prevent-spawn-when-player-is-in-fire: false

# When a player presses the SHIFT button while teleporting, and sits in snake mode, will it cancel teleportation?
# This ignores with setthespawn.bypass.sneak permission.
check-sneak-while-teleport:
  enable: false
  message: "&cTeleporting is canceled because snake mode is enabled."

# Cost /spawn command or sign usage.
# For this requires a Vault plugin.
spawn-cost:
  enable: false

  enable-permission: true
  # If this is specified at the group, they can use the /spawn command without payment.
  # If not specified, the /spawn command must be paid.
  permission: setthespawn.bypass.spawncost

  # This can be set as per-spawn when setting the spawn point.
  cost: 3.0

  # Sign usage price. (Same as /spawn command.)
  sign:
    enable: false

    enable-permission: true
    # If this is specified at the rank, they can use the spawn sign without payment.
    # If not specified, the spawn sign usage must be paid.
    permission: setthespawn.bypass.signcost

    # Cost of sign usage
    cost: 2.0

# Cancel teleport if:
cancel-teleport:
  # Player was moved while teleporting.
  move:
    enable: true

    # Message when the player moved.
    teleport-canceled: "&cTeleport cancelled, you can't move!"

    # If true when the player moves, the teleport delay will cancel.
    # If false when the player moves, the teleport delay does NOT cancel it.
    enable-permission: true
    permission: setthespawn.bypass.movement

    # Play sound when a player moved while teleporting.
    play-sound:
      enable: true

      # Usage: SOUND_TYPE, volume, pitch
      type: BLOCK_PORTAL_TRAVEL, 8, 1

    # If the player moved during teleporting, would the player pay for it or not?
    pay-if-moved:
      enable: false

      # Cost for moved during teleport
      cost: 3.50

      # The permission to bypass move
      enable-permission: true
      permission: setthespawn.bypass.spawn.movedcost

      # Use %cost% placeholder.
      no-money: "&cYou do not have enough money to move during teleport.&e Cost:&a $%cost%"

  # Player was jump while teleporting.
  jump:
    enable: true

    # Message when the player jumped.
    teleport-canceled: "&cTeleport cancelled, you can't jump!"

    # If true when the player jump, the teleport delay will cancel.
    # If false when the player jump, the teleport delay does NOT cancel it.
    enable-permission: true
    permission: setthespawn.bypass.jump

    # Play sound when a player jump while teleporting.
    play-sound:
      enable: true

      # Usage: SOUND_TYPE, volume, pitch
      type: BLOCK_WOODEN_DOOR_CLOSE, 8, 1

    # If the player jumped during teleporting, would the player pay for it or not?
    pay-if-jumped:
      enable: true

      # Cost for jumped during teleport
      cost: 1.00

      # The permission to bypass jump
      enable-permission: true
      permission: setthespawn.bypass.spawn.jumpedcost

      # Use %cost% placeholder.
      no-money: "&cYou do not have enough money to jump in teleport.&e Cost:&a $%cost%"

  # When the player is attacked while teleporting.
  damage:
    enable: true

    # Message when the other player attacked.
    teleport-canceled: "&cTeleport cancelled, you are in combat!"

    # If true when the player is attacked, the teleport delay will cancel.
    # If false when the player is attacked, the teleport delay does NOT cancel it.
    enable-permission: true
    permission: setthespawn.bypass.damage

    # Play sound when a player attacked someone while teleporting.
    play-sound:
      enable: true

      # Usage: SOUND_TYPE, volume, pitch
      type: BLOCK_LEVER_CLICK, 8, 1

    # If the player damage during teleporting, would the player pay for it or not?
    pay-if-damage:
      enable: false

      # Cost for get damage during teleport
      cost: 0.5

      # The permission to bypass cancel teleport for got damage
      enable-permission: true
      permission: setthespawn.bypass.spawn.damagecost

      # Use %cost% placeholder.
      no-money: "&cYou do not have enough money for the teleport damage.&e Cost:&a $%cost%"

# When a player is being teleported, will plays an effect?
teleport-effect:
  enable: true

  # All effects:
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html
  # Usage: EFFECT_TYPE, duration
  effect: ENDER_SIGNAL, 10

# Teleport sound playback.
teleport-sound:
  enable: true

  # All sounds:
  # 1.7.x: https://jd.bukkit.org/org/bukkit/Sound.html
  # 1.8.x: http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html
  # 1.9.x - 1.13.x: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  # Usage: SOUND_TYPE, volume, pitch
  sound: ENDERMAN_TELEPORT, 10, 1

# Launch firework when the player teleported to the spawn.
launch-firework:
  enable: true

  # If true, the features below do not apply to it.
  random: true
  flicker: true
  trail: true

  # All firework types: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/FireworkEffect.Type.html
  type: STAR

  # Colors 0 - 255
  colors:
  - 229,0,0
  - 0,80,0
  - 0,0,103

  # The power to launch the firework.
  power: 1

# Send title if:
title:
  # When you have started teleporting, a title will also be displayed.
  start-spawn:
    enable: true

    # Use %seconds% placeholder.
    title: "&aTeleporting in"
    subtitle: "&6%seconds%&a seconds"

    # The time it takes for the title to fade into the screen. (In ticks)
    fade-in: 10
    # The time it takes for the title to stay on the screen. (In ticks)
    stay: 30
    # The time it takes for the title to fade out of the screen. (In ticks)
    fade-out: 60
  # This is when the player has teleported to the spawn and displays the title.
  end-spawn:
    enable: true

    title: "&3Teleport"
    subtitle: "&asuccess!"

    # The time it takes for the title to fade into the screen. (In ticks)
    fade-in: 10
    # The time it takes for the title to stay on the screen. (In ticks)
    stay: 30
    # The time it takes for the title to fade out of the screen. (In ticks)
    fade-out: 60
  # When a player moves while teleporting.
  player-moved:
    enable: true

    title: "&cYou moved!"
    subtitle: "&eTeleport cancelled."

    # The time it takes for the title to fade into the screen. (In ticks)
    fade-in: 10
    # The time it takes for the title to stay on the screen. (In ticks)
    stay: 30
    # The time it takes for the title to fade out of the screen. (In ticks)
    fade-out: 50
  # When a player jump while teleporting.
  player-jump:
    enable: true

    title: "&cYou jumped!"
    subtitle: "&eTeleport cancelled."

    # The time it takes for the title to fade into the screen. (In ticks)
    fade-in: 10
    # The time it takes for the title to stay on the screen. (In ticks)
    stay: 30
    # The time it takes for the title to fade out of the screen. (In ticks)
    fade-out: 50
  # When teleporting player are attacked while teleporting.
  player-damage:
    enable: true

    title: "&cA player was attacked!"
    subtitle: "&eTeleport cancelled."

    # The time it takes for the title to fade into the screen. (In ticks)
    fade-in: 10
    # The time it takes for the title to stay on the screen. (In ticks)
    stay: 30
    # The time it takes for the title to fade out of the screen. (In ticks)
    fade-out: 50

# When does the player void, will the player teleport to the spawn?
void-on-spawn:
  enable: true

  # At that point, the player will be teleported to the spawn.
  # Example: 5 - so Y:5.
  height: 0

  # If it is true, it does not hurt.
  # If it is false, it hurts.
  fall-distance: true

  # When a player void, plays an effect?
  teleport-effect:
    enable: true

    # All effects:
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html
    effect: ENDER_SIGNAL, 15

  # Message when the player has void fall and teleported to spawn.
  message: ""

# Teleport on command when the player teleported to spawn.
teleport-on-command:
  enable: true

  # Use %player%, %player-displayname%, %world%, %player-gamemode%, %player-health%, %player-max-health% placeholder.
  # Use player & console arguments for first.
  commands:
  - "player: money"
  - "player: kit"
  - "console: eco take %player% 50"
  - "console: money"

# Teleport to spawn if:
spawn-teleport:
  # If the player joins the server, will it teleport to the spawn?
  player-join: false

  # If the player first joins the server, will it teleport to the spawn?
  player-first-join: true

  # When the player is died and teleported to the spawn.
  respawn: true

# Spawn sign settings.
spawn-sign:
  # Allows you to create and use the spawn sign.
  enable: true

  # Save signs automatically to a file when you place a sign?
  save-sign-data: false

  # If the player does not have permission to create a sign.
  no-permission-create-sign:
    # If it is true, it will break the sign.
    # If it is false, it does not break the sign.
    break-sign: false

    # If this enabled then writes the lines to sign.
    setline:
      enable: true

      lines:
      - "&cYou do not have"
      - "&cpermission"
      - "&cto create"
      - "&ca sign!"

  # If the spawn is not set up and what to write.
  # Use %text% placeholder.
  no-spawn:
  - "&c[Spawn]"
  - "%text%"
  - "%text%"
  - "%text%"

  # If the spawn is set and what to write.
  spawn-created:
    lines:
    - "&9[Spawn]"
    - "%text%"
    - "%text%"
    - "%text%"

    # Use %all% placeholder.
    everybody:
    - "&9[Spawn]"
    - "%all%"
    - "%text%"
    - "%text%"

    # If the world spawn is set and what to write.
    per-world:
      # Use %world% placeholder.
      lines:
      - "&9[Spawn]"
      - "&6%world%"
      - "%text%"
      - "%text%"

      # Use %all%, %world% placeholder.
      everybody:
      - "&9[Spawn]"
      - "%all%"
      - "%world%"
      - "%text%"

  # Play particle effect when a user creates a spawn sign?
  play-particle-effect-on-sign-create:
    enable: true

    # All particle effects: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
    type: EXPLOSION_LARGE, 5

# Enable the gui setup?
enable-gui: false

# How many rows should the GUI have?
gui-rows: 1

# What should the name of the GUI be?
gui-name: "&5Spawn settings"

# Close the GUI when a player clicks on an item?
close-gui-when-player-clicked-on-a-item: true

# All GUI items are here. Add slots in the same format, and it will add items to the GUI.
# How to add new item in GUI?: https://github.com/montlikadani/SetTheSpawn/wiki/How-to-add-new-item-to-GUI%3F%E2%80%8B
# Slot starts at 0 and end at 53 for a size 54 inventory.
items:
  slot-0:
    item: AIR
    command: ""
  slot-1:
    item: AIR
    command: ""
  slot-2:
    item: SIGN
    durability: 0
    name: "&3Setspawn"
    lore:
      - "&7------------"
      - "&aSet spawn command."
      - "&7------------"
    command: setspawn
  slot-3:
    item: AIR
    command: ""
  slot-4:
    item: ENDER_PEARL
    durability: 0
    name: "&6Teleport"
    lore:
      - "&7------------"
      - "&aTeleport to the spawn."
      - "&7------------"
    command: spawn
  slot-5:
    item: AIR
    command: ""
  slot-6:
    item: BONE
    durability: 0
    name: "&4Delete spawn"
    lore:
      - "&7------------"
      - "&5Delete spawn location."
      - "&7------------"
    command: delspawn

#=========================================#
#             Plugin Settings             #
#=========================================#
# bStats Metrics
metrics: true

# Check for updates.
check-update: true

# Log plugin messages into console.
logconsole: true

# Logging to file messages.
log-to-file: true

# Plugin enable/disable messages in console.
# Use %newline% placeholder.
plugin-enable: '&6[&9Set&2The&4Spawn&6]&7 >&a The plugin successfully enabled&6 v2.4&a!'
plugin-disable: '&6[&9Set&2The&4Spawn&6]&7 >&c The plugin successfully disabled!'

# DO NOT CHANGE THIS!
config-version: 7
```
